version: '3.8'

services:

  server:
    restart: always
    build: .
    command: >
      sh -c "cd /app/school_event_management_system/
      && python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ${ENV}

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - ${ENV}
    ports:
      - "6380:6379"

  celery:
    restart: always
    env_file:
      - ${ENV}
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "cd /app/school_event_management_system/
      && celery -A config worker -l info"
    links:
      - redis
    depends_on:
      - redis
      - server
