# Generated by Django 4.2.7 on 2023-11-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDiplomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='ссылка на дипломы')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='мероприятие')),
            ],
            options={
                'verbose_name': 'Дипломы мероприятия',
                'verbose_name_plural': 'Дипломы мероприятий',
            },
        ),
    ]
