# Generated by Django 4.2.7 on 2023-11-23 18:57

import phonenumber_field.modelfields

import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_team_supervisor_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо ввести в формате: +XXXXXXXXXXXXX.', regex='^\\+?[0-9]{7,15}$')], verbose_name='номер телефона'),
        ),
    ]
