# Generated by Django 4.2.7 on 2023-12-03 10:21

from django.db import migrations, models

import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='regulations',
            field=models.FileField(blank=True, null=True, upload_to=events.models.get_event_regulations_upload_path, verbose_name='регламент мероприятия'),
        ),
    ]
