# Generated by Django 4.2.7 on 2023-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='url',
            field=models.URLField(blank=True, verbose_name='ссылка на файлы'),
        ),
    ]
