# Generated by Django 4.2.7 on 2023-12-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_solution_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='school_class',
            field=models.CharField(blank=True, max_length=5, verbose_name='класс который представляет команда'),
        ),
    ]
