# Generated by Django 4.2.7 on 2023-12-08 20:57

import ckeditor.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_team_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание мероприятия'),
        ),
    ]
