# Generated by Django 4.2.7 on 2023-12-13 20:50

import ckeditor.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='описание мероприятия')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='мероприятие')),
            ],
            options={
                'verbose_name': 'Задание мероприятия',
                'verbose_name_plural': 'Задания мероприятий',
            },
        ),
    ]
