# Generated by Django 4.2.7 on 2023-12-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='need_presentation',
            field=models.BooleanField(blank=True, default=False, verbose_name='нужна презентация'),
        ),
    ]
