# Generated by Django 4.2.7 on 2023-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_task_description_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_ending_registration',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания регистрации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_starting_event',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_starting_registration',
            field=models.DateField(blank=True, null=True, verbose_name='дата начала регистрации'),
        ),
    ]
