# Generated by Django 4.2.7 on 2023-12-24 10:26

import ckeditor_uploader.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_date_of_ending_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='задание мероприятия'),
        ),
    ]
