# Generated by Django 4.2.7 on 2024-01-11 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_description_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maximum_number_of_team_members',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='максимальное количество участников в команде'),
        ),
        migrations.AlterField(
            model_name='event',
            name='minimum_number_of_team_members',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='минимальное количество участников в команде'),
        ),
    ]
