# Generated by Django 4.2.7 on 2024-01-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_participant_supervisor_fio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='тема проекта'),
        ),
    ]
