# Generated by Django 4.2.7 on 2024-01-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_solution_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предмет'),
        ),
    ]
