# Generated by Django 4.2.7 on 2024-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_solution_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.CharField(blank=True, choices=[('Школьный', 'Школьный'), ('Районный', 'Районный'), ('Городской', 'Городской'), ('Региональный', 'Региональный'), ('Всероссийский', 'Всероссийский'), ('Международный', 'Международный')], default='Школьный', max_length=50, verbose_name='уровень мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Индивидуальное', 'Индивидуальное'), ('Индивидуальное, коллективное', 'Индивидуальное, коллективное'), ('Командное', 'Командное'), ('Командное от классов', 'Командное от классов')], max_length=50, verbose_name='тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='тема проекта'),
        ),
    ]
