# Generated by Django 4.2.7 on 2024-01-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_stage_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='theses',
            field=models.CharField(default='', max_length=5120, verbose_name='Краткие тезисы'),
            preserve_default=False,
        ),
    ]
