# Generated by Django 4.2.7 on 2024-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_solution_options_participant_fio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='need_account',
            field=models.BooleanField(blank=True, default=True, verbose_name='нужен аккаунт у участников'),
        ),
    ]
