# Generated by Django 4.2.7 on 2024-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='from_current_school',
            field=models.BooleanField(blank=True, default=True, verbose_name='из '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ученик', 'ученик'), ('учитель', 'учитель'), ('другая', 'другая')], default='ученик', max_length=10, verbose_name='роль'),
        ),
    ]
