# Generated by Django 4.2.7 on 2024-01-16 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_from_current_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='from_current_school',
            field=models.BooleanField(blank=True, default=True, verbose_name='из ГБОУ гимназия № 426'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default='ГБОУ гимназия № 426', max_length=255, verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_study',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'Не обучаюсь в школе'), (1, '1-й класс'), (2, '2-й класс'), (3, '3-й класс'), (4, '4-й класс'), (5, '5-й класс'), (6, '6-й класс'), (7, '7-й класс'), (8, '8-й класс'), (9, '9-й класс'), (10, '10-й класс'), (11, '11-й класс')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='год обучения'),
        ),
    ]
